import"./assets/main-B_zSWVXd.js";import"./assets/vendor-BWC8OeqA.js";const v="98ff2d6267ceea8e039422b0f46fb813",m="https://api.themoviedb.org/3",k="https://image.tmdb.org/t/p/w500",p=document.getElementById("moviesContainer"),f=document.getElementById("emptyMessage");let i="",c="";E();function E(){fetch(`${m}/trending/movie/week?api_key=${v}`).then(e=>e.json()).then(e=>{e.results.length===0?_():$(e.results)})}function $(e){f.hidden=!0,p.innerHTML="",e.slice(0,10).forEach(n=>{const t=`
      <a href="catalog_mainbody.html?id=${n.id}" class="movie-card">
        <img src="${k+n.poster_path}" alt="${n.title}">
        <h3>${n.title}</h3>
      </a>
    `;p.insertAdjacentHTML("beforeend",t)})}function _(){p.innerHTML="",f.hidden=!1}const d=document.getElementById("yearBtn"),l=document.getElementById("yearDropdown"),M=document.getElementById("selectedYear");d.addEventListener("click",e=>{e.stopPropagation(),l.classList.toggle("open"),d.classList.toggle("open")});l.addEventListener("click",e=>{e.target.tagName==="LI"&&(i=e.target.dataset.year,M.textContent=e.target.textContent,l.classList.remove("open"),d.classList.remove("open"),c&&L(1))});document.addEventListener("click",()=>{l.classList.remove("open"),d.classList.remove("open")});document.querySelector(".search-input");const b=document.querySelector(".search-input1"),w=document.querySelector(".search-btn");w.addEventListener("click",()=>{if(c=b.value.trim(),!c&&!i){E();return}L(1)});function L(e=1){const n=c?`${m}/search/movie`:`${m}/discover/movie`,t=new URL(n);t.searchParams.append("api_key",v),t.searchParams.append("page",e),c&&t.searchParams.append("query",c),i&&t.searchParams.append("primary_release_year",i),fetch(t).then(o=>o.json()).then(o=>{if(!o.results||o.results.length===0){_();return}$(o.results)}).catch(o=>console.error("Arama hatası:",o))}const A={28:"Action",12:"Adventure",16:"Animation",35:"Comedy",80:"Crime",18:"Drama",10751:"Family",14:"Fantasy",27:"Horror",9648:"Mystery",878:"Sci-Fi",53:"Thriller",10749:"Romance"},g="98ff2d6267ceea8e039422b0f46fb813",u="https://api.themoviedb.org/3",B="https://image.tmdb.org/t/p/w500",x=new URLSearchParams(window.location.search);x.get("id");fetch(`${u}/trending/movie/week?api_key=${g}`).then(e=>e.json()).then(e=>{S(e.results)});function C(e){const n=Math.round(e/2);let t="";for(let o=1;o<=5;o++)t+=o<=n?"★":"☆";return t}function S(e){const n=document.getElementById("weeklyTrends");n.innerHTML="",e.slice(0,1).forEach(t=>{var h;const o=C(t.vote_average),s=t.genre_ids.map(I=>A[I]).filter(Boolean).slice(0,2).join(", "),r=t.poster_path?B+t.poster_path:"./images/no-poster.jpg",a=`
  <a href="catalog_mainbody.html?id=${t.id}" class="movie-card large">

    <img src="${r}" alt="${t.title}">

    <div class="movie-card-overlay">
      <div class="movie-card-text">
        <h3 class="movie-title">${t.title}</h3>
        <p class="movie-meta">${s} | ${(h=t.release_date)==null?void 0:h.split("-")[0]}</p>
      </div>

      <div class="movie-card-rating">
        ${o}
      </div>
    </div>
     </a>
    `;n.insertAdjacentHTML("beforeend",a)})}j();function j(){const e=new Date,n=e.getFullYear(),t=String(e.getMonth()+1).padStart(2,"0"),o=`${n}-${t}-01`,s=`${n}-${t}-31`;fetch(`${u}/discover/movie?api_key=${g}&language=en-US&primary_release_date.gte=${o}&primary_release_date.lte=${s}&sort_by=popularity.desc`).then(r=>r.json()).then(r=>{if(!r.results||r.results.length===0){console.warn("Ayın filmi bulunamadı");return}const a=r.results[0];D(a.id)})}function D(e){fetch(`${u}/movie/${e}?api_key=${g}&language=en-US`).then(n=>n.json()).then(n=>{P(n)})}function P(e){document.getElementById("movieTitle").textContent=e.title,document.getElementById("movieDate").textContent=e.release_date.split("-").reverse().join("."),document.getElementById("movieGenre").textContent=e.genres.map(s=>s.name).join(", "),document.getElementById("moviePopularity").textContent=e.popularity.toFixed(1);const n=document.getElementById("heroBackdrop");n&&e.backdrop_path&&(n.src=B+e.backdrop_path);const t=(s,r)=>{const a=document.getElementById(s);a&&(a.textContent=r)},o=e.genres.map(s=>s.name).join(", ");t("movieDate",e.release_date),t("movieVote",`${e.vote_average.toFixed(1)} / ${e.vote_count}`),document.getElementById("movieDate").textContent=e.release_date.split("-").reverse().join("."),document.getElementById("movieGenre").textContent=e.genres.map(s=>s.name).join(", "),document.getElementById("movieVoteAvg").textContent=e.vote_average.toFixed(1),document.getElementById("movieVoteCount").textContent=e.vote_count,document.getElementById("moviePopularity").textContent=e.popularity.toFixed(1),t("moviePopularity",e.popularity.toFixed(1)),t("movieGenre",o),t("movieOverview",e.overview)}const T="98ff2d6267ceea8e039422b0f46fb813",F="https://api.themoviedb.org/3/trending/movie/day";fetch(`${F}?api_key=${T}`).then(e=>e.json()).then(e=>{const n=e.results.slice(0,9);H(n)}).catch(console.error);const y=document.getElementById("movieList");function H(e){y.innerHTML="",e.forEach(n=>{var o;const t=document.createElement("article");t.className="movie-card",t.innerHTML=`
      <img src="https://image.tmdb.org/t/p/w500${n.poster_path}" alt="${n.title}">
      <div class="movie-info">
        <h3>${n.title}</h3>
        <p>${n.genre} | ${(o=n.release_date)==null?void 0:o.slice(0,4)}</p>
      </div>
    `,y.appendChild(t)})}document.addEventListener("DOMContentLoaded",()=>{const e=document.getElementById("genreBtn"),n=document.getElementById("genreDropdown"),t=document.getElementById("genreIcon"),o=n.querySelectorAll("li");e.addEventListener("click",s=>{s.stopPropagation(),n.classList.toggle("active"),t.classList.toggle("rotate")}),o.forEach(s=>{s.addEventListener("click",r=>{r.stopPropagation(),n.classList.remove("active"),t.classList.remove("rotate")})}),document.addEventListener("click",()=>{n.classList.remove("active"),t.classList.remove("rotate")}),document.addEventListener("keydown",s=>{s.key==="Escape"&&(n.classList.remove("active"),t.classList.remove("rotate"))})});
//# sourceMappingURL=index.js.map
